### PR TITLE
Add AI voice

### PR DESCRIPTION
**Pull request by SuZhou-Joe**
image

The voice is not so good in Chinese.

Further more, because nextJS do not support stream response. It takes some time to adapt to the response of ElevenLabs, the total effort is 1.5h .

### CODE REVIEW

**Comment by SuZhou-Joe** [comment]
#7

**Comment by javenisme** [comment]
Looks good. But
- Talking with AIMentor means the user can input with voice also. 
- Please modify the play button in the right place.

Screenshot 2023-06-06 at 10 22 48 PM

**Comment by SuZhou-Joe** [comment]
> Looks good. But
> 
> * Talking with AIMentor means the user can input with voice also.
> * Please modify the play button in the right place.
> 
> Screenshot 2023-06-06 at 10 22 48 PM
> 
> https://www.chatwithgpt.ai/chat/ec65bb5b-46ec-4672-be6d-be0ae21d6584

Sorry but for the second task, I need 1 more hour to integrate with openai speech-to-text API and browser's microphone, please confirm here if it is OK for you.

**Comment by SuZhou-Joe** [comment]
image
Done for speech-to-text

**Pull request merged**
